// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteApp.Data;

#nullable disable

namespace RestauranteApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestauranteApp.Models.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Atendimentos");

                    b.HasDiscriminator<string>("TipoAtendimento").HasValue("Atendimento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RestauranteApp.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("RestauranteApp.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Arroz"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Feijão"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Frango"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Carne Bovina"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Alface"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Tomate"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Macarrão"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Molho de Tomate"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Queijo"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Presunto"
                        });
                });

            modelBuilder.Entity("RestauranteApp.Models.ItemCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ItensCardapio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Frango grelhado com salada",
                            Nome = "Frango Grelhado",
                            Periodo = 1,
                            PrecoBase = 35.90m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Arroz, feijão, carne e salada",
                            Nome = "PF Completo",
                            Periodo = 1,
                            PrecoBase = 28.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Macarrão com molho de tomate",
                            Nome = "Macarrão ao Sugo",
                            Periodo = 1,
                            PrecoBase = 25.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Filé de peixe assado com legumes",
                            Nome = "Peixe Assado",
                            Periodo = 1,
                            PrecoBase = 42.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Salada com croutons e molho caesar",
                            Nome = "Salada Caesar",
                            Periodo = 1,
                            PrecoBase = 22.00m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Bife com cebola caramelizada",
                            Nome = "Bife Acebolado",
                            Periodo = 1,
                            PrecoBase = 38.00m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Risoto cremoso de frango",
                            Nome = "Risoto de Frango",
                            Periodo = 1,
                            PrecoBase = 32.00m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Feijoada completa",
                            Nome = "Feijoada",
                            Periodo = 1,
                            PrecoBase = 45.00m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Moqueca com leite de coco",
                            Nome = "Moqueca de Tilápia",
                            Periodo = 1,
                            PrecoBase = 48.00m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Wrap com frango e legumes",
                            Nome = "Wrap de Frango",
                            Periodo = 1,
                            PrecoBase = 27.00m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Espaguete com molho cremoso",
                            Nome = "Espaguete Carbonara",
                            Periodo = 1,
                            PrecoBase = 33.00m
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Frango empanado com molho",
                            Nome = "Frango à Parmegiana",
                            Periodo = 1,
                            PrecoBase = 36.00m
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Strogonoff com arroz e batata",
                            Nome = "Strogonoff de Carne",
                            Periodo = 1,
                            PrecoBase = 39.00m
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Hambúrguer com queijo e bacon",
                            Nome = "Hambúrguer Artesanal",
                            Periodo = 1,
                            PrecoBase = 34.00m
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Omelete recheado com legumes",
                            Nome = "Omelete de Legumes",
                            Periodo = 1,
                            PrecoBase = 22.00m
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Caldo grosso com torresmo",
                            Nome = "Caldo de Feijão",
                            Periodo = 1,
                            PrecoBase = 18.00m
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Carne assada com mandioca",
                            Nome = "Carne Assada",
                            Periodo = 1,
                            PrecoBase = 41.00m
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Panqueca recheada com molho",
                            Nome = "Panqueca de Carne",
                            Periodo = 1,
                            PrecoBase = 29.00m
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Filé com purê de batatas",
                            Nome = "Filé de Frango",
                            Periodo = 1,
                            PrecoBase = 37.00m
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Opção vegetariana variada",
                            Nome = "Vegetariano do Dia",
                            Periodo = 1,
                            PrecoBase = 24.00m
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Picanha ao ponto com vinagrete",
                            Nome = "Picanha Grelhada",
                            Periodo = 2,
                            PrecoBase = 75.00m
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "Salmão com molho de ervas",
                            Nome = "Salmão ao Molho",
                            Periodo = 2,
                            PrecoBase = 68.00m
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "Fraldinha marinada em vinho tinto",
                            Nome = "Fraldinha ao Vinho",
                            Periodo = 2,
                            PrecoBase = 62.00m
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "Camarão grelhado na manteiga",
                            Nome = "Camarão na Manteiga",
                            Periodo = 2,
                            PrecoBase = 72.00m
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "Risoto cremoso de camarão",
                            Nome = "Risoto de Camarão",
                            Periodo = 2,
                            PrecoBase = 65.00m
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "Carré de cordeiro com legumes",
                            Nome = "Cordeiro Assado",
                            Periodo = 2,
                            PrecoBase = 89.00m
                        },
                        new
                        {
                            Id = 27,
                            Descricao = "Nhoque artesanal ao sugo",
                            Nome = "Nhoque de Batata",
                            Periodo = 2,
                            PrecoBase = 45.00m
                        },
                        new
                        {
                            Id = 28,
                            Descricao = "Filé mignon ao molho madeira",
                            Nome = "Filé Mignon",
                            Periodo = 2,
                            PrecoBase = 85.00m
                        },
                        new
                        {
                            Id = 29,
                            Descricao = "Bacalhau com batatas e azeitonas",
                            Nome = "Bacalhau Gratinado",
                            Periodo = 2,
                            PrecoBase = 78.00m
                        },
                        new
                        {
                            Id = 30,
                            Descricao = "Frango recheado com farofa",
                            Nome = "Frango Recheado",
                            Periodo = 2,
                            PrecoBase = 52.00m
                        },
                        new
                        {
                            Id = 31,
                            Descricao = "Polvo com azeite e batata",
                            Nome = "Polvo Grelhado",
                            Periodo = 2,
                            PrecoBase = 82.00m
                        },
                        new
                        {
                            Id = 32,
                            Descricao = "Pato com geleia de laranja",
                            Nome = "Magret de Pato",
                            Periodo = 2,
                            PrecoBase = 91.00m
                        },
                        new
                        {
                            Id = 33,
                            Descricao = "Atum selado com gergelim",
                            Nome = "Steak de Atum",
                            Periodo = 2,
                            PrecoBase = 74.00m
                        },
                        new
                        {
                            Id = 34,
                            Descricao = "Costela bovina assada lentamente",
                            Nome = "Costela ao Forno",
                            Periodo = 2,
                            PrecoBase = 67.00m
                        },
                        new
                        {
                            Id = 35,
                            Descricao = "Ravioli recheado com funghi",
                            Nome = "Ravioli de Funghi",
                            Periodo = 2,
                            PrecoBase = 55.00m
                        },
                        new
                        {
                            Id = 36,
                            Descricao = "Peixe branco com molho de creme",
                            Nome = "Peixe ao Creme",
                            Periodo = 2,
                            PrecoBase = 59.00m
                        },
                        new
                        {
                            Id = 37,
                            Descricao = "Lula recheada ao forno",
                            Nome = "Lula Recheada",
                            Periodo = 2,
                            PrecoBase = 63.00m
                        },
                        new
                        {
                            Id = 38,
                            Descricao = "Carré com crosta de ervas",
                            Nome = "Carré de Porco",
                            Periodo = 2,
                            PrecoBase = 70.00m
                        },
                        new
                        {
                            Id = 39,
                            Descricao = "Combinação de carne e frango",
                            Nome = "Duo de Proteínas",
                            Periodo = 2,
                            PrecoBase = 79.00m
                        },
                        new
                        {
                            Id = 40,
                            Descricao = "Prato vegetariano elaborado",
                            Nome = "Jantar Vegetariano",
                            Periodo = 2,
                            PrecoBase = 48.00m
                        });
                });

            modelBuilder.Entity("RestauranteApp.Models.ItemCardapioIngrediente", b =>
                {
                    b.Property<int>("ItemCardapioId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.HasKey("ItemCardapioId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ItemCardapioIngredientes");
                });

            modelBuilder.Entity("RestauranteApp.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Capacidade = 2,
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Capacidade = 4,
                            Numero = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Capacidade = 4,
                            Numero = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Capacidade = 6,
                            Numero = 4
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            Capacidade = 8,
                            Numero = 5
                        });
                });

            modelBuilder.Entity("RestauranteApp.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodoPedido")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RestauranteApp.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FoiSugestaoChefe")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCardapioId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemCardapioId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("RestauranteApp.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoConfirmacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPessoas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("RestauranteApp.Models.SugestaoChefe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemCardapioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemCardapioId");

                    b.HasIndex("Data", "Periodo")
                        .IsUnique();

                    b.ToTable("SugestoesChefe");
                });

            modelBuilder.Entity("RestauranteApp.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RestauranteApp.Models.AtendimentoDeliveryAplicativo", b =>
                {
                    b.HasBaseType("RestauranteApp.Models.Atendimento");

                    b.Property<string>("EnderecoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAplicativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DeliveryAplicativo");
                });

            modelBuilder.Entity("RestauranteApp.Models.AtendimentoDeliveryProprio", b =>
                {
                    b.HasBaseType("RestauranteApp.Models.Atendimento");

                    b.Property<string>("EnderecoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxaFixa")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("Atendimentos", t =>
                        {
                            t.Property("EnderecoEntrega")
                                .HasColumnName("AtendimentoDeliveryProprio_EnderecoEntrega");
                        });

                    b.HasDiscriminator().HasValue("DeliveryProprio");
                });

            modelBuilder.Entity("RestauranteApp.Models.AtendimentoPresencial", b =>
                {
                    b.HasBaseType("RestauranteApp.Models.Atendimento");

                    b.Property<int?>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Presencial");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RestauranteApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RestauranteApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RestauranteApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteApp.Models.Endereco", b =>
                {
                    b.HasOne("RestauranteApp.Models.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestauranteApp.Models.ItemCardapioIngrediente", b =>
                {
                    b.HasOne("RestauranteApp.Models.Ingrediente", "Ingrediente")
                        .WithMany("ItemCardapioIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Models.ItemCardapio", "ItemCardapio")
                        .WithMany("ItemCardapioIngredientes")
                        .HasForeignKey("ItemCardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("ItemCardapio");
                });

            modelBuilder.Entity("RestauranteApp.Models.Pedido", b =>
                {
                    b.HasOne("RestauranteApp.Models.Atendimento", "Atendimento")
                        .WithMany("Pedidos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Atendimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestauranteApp.Models.PedidoItem", b =>
                {
                    b.HasOne("RestauranteApp.Models.ItemCardapio", "ItemCardapio")
                        .WithMany("PedidoItens")
                        .HasForeignKey("ItemCardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Models.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCardapio");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("RestauranteApp.Models.Reserva", b =>
                {
                    b.HasOne("RestauranteApp.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestauranteApp.Models.SugestaoChefe", b =>
                {
                    b.HasOne("RestauranteApp.Models.ItemCardapio", "ItemCardapio")
                        .WithMany("SugestoesChefe")
                        .HasForeignKey("ItemCardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCardapio");
                });

            modelBuilder.Entity("RestauranteApp.Models.Atendimento", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("RestauranteApp.Models.Ingrediente", b =>
                {
                    b.Navigation("ItemCardapioIngredientes");
                });

            modelBuilder.Entity("RestauranteApp.Models.ItemCardapio", b =>
                {
                    b.Navigation("ItemCardapioIngredientes");

                    b.Navigation("PedidoItens");

                    b.Navigation("SugestoesChefe");
                });

            modelBuilder.Entity("RestauranteApp.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("RestauranteApp.Models.Pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("RestauranteApp.Models.Usuario", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
